[package]
name = "fraudguard"
edition = "2024.beta"
license = "MIT"
authors = ["FraudGuard Team"]

[dependencies]
# Sui framework dependencies are automatically included

[addresses]
fraudguard = "0xa97d9b127b18afe9cc4c42f3fdab5c5044fa2c2aa2d2883049e009e0ea1cacf1"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.